# Site settings
title: Synereo Blog
email: founders@synereo.com
description: The Decentralized and Distributed Social Network
baseurl: ""
url: "http://newblog.synereo.com"
twitter_username: synereo
github_username:  synereo

# Build settings
markdown: kramdown
