# Site settings
title: Synereo Blog
email: founders@synereo.com
description: The Decentralized and Distributed Social Network
baseurl: ""
url: "http://blog.synereo.com"
twitter_username: synereo
github_username:  synereo

permalink: pretty
paginate: 4
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
